version: "3.8"

services:
  # MySQL Service
  mysql:
    image: mysql:8.0
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    container_name: lapcity-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 150577
      MYSQL_DATABASE: lapcitydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: 150577
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # Node.js Service
  app:
    container_name: lapcity-node
    build:
      context: ./nodejs
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: 150577
      DB_NAME: lapcitydb
      DB_PORT: 3306
    volumes:
      - .:/usr/src/app
    restart: always

volumes:
  mysql-data:
    driver: local